export const GET_POSTS = 'GET_POSTS'
export const SAVE_POST = 'SAVE_POST'
export const DELETE_POST = 'DELETE_POST'
export const SET_MESSAGE = 'SET_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const LOADING_INI = 'LOADING_INI'
export const LOADING_OFF = 'LOADING_OFF'
